using CleanArchitecture.Core.Entities.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CleanArchitecture.Web.ApiModels.Core
{
    public class PersonModel : BaseModel<Person>
    {
        public string identityNumber { get; set; }
        public string fullname { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string displayname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int gender { get; set; }
        public string country { get; set; }
        public DateTime? birthday { get; set; }
        public PersonModel()
        {

        }

        public void AutoGenerateDisplayName()
        {
            if (String.IsNullOrEmpty(displayname))
            {
                displayname = firstname + " " + lastname;
            }
        }

        public void AutoGenerateFullName()
        {
            if (String.IsNullOrEmpty(fullname))
            {
                fullname = firstname + " " + lastname;
            }
        }

        public PersonModel(Person entity) : base(entity)
        {
            identityNumber = entity.IdentityNumber;
            fullname = entity.FullName;
            firstname = entity.FirstName;
            lastname = entity.LastName;
            displayname = entity.DisplayName;
            address = entity.Address;
            phone = entity.Phone;
            email = entity.Email;
            gender = entity.Gender;
            country = entity.Country == null ? "" : entity.Country.Name;
            birthday = entity.Birthday;
        }

        public Person ToEntity()
        {
            var person = new Person
            {
                IdentityNumber = identityNumber,
                FullName = fullname,
                FirstName = firstname,
                LastName = lastname,
                DisplayName = displayname,
                Address = address,
                Phone = phone,
                Email = email,
                Gender = gender,
                Birthday = birthday,
                CountryId = 1
            };
            return person;
        }
    }
}
